### ISSUE TITLE
compilation error in pcf8591.cpp

### ISSUE THREAD

**Issue by jsqq** [RobTillaart/PCF8591#1]
in line 112 
instead of 

return PCF8591_I2C_ERROR;

should be

_error = PCF8591_I2C_ERROR;
return;

**Comment by RobTillaart** [comment]
@jsqq
Sorry to react so late (3 months is way too long) but apparently I missed it.

In the meantime the library is compiling. In fact I'm working to get all my libs under Arduino CI build optionally with unit tests. That should prevent things like non-compilation happening.

Are there still issues with this lib, as I will spend some time on it tomorrow. #3 

Again apologies for the inconveniences,

**Comment by RobTillaart** [comment]
As I got no answer I close the issue.
Expect 0.1.1 release soon!

**Comment by jsqq** [comment]
> 
> 
> @jsqq
> Sorry to react so late (3 months is way too long) but apparently I missed it.
> 
> In the meantime the library is compiling. In fact I'm working to get all my libs under Arduino CI build optionally with unit tests. That should prevent things like non-compilation happening.
> 
> Are there still issues with this lib, as I will spend some time on it tomorrow. #3
> 
> Again apologies for the inconveniences,

Sorry for my late answer. Thank you. I glad (hope) that I been helpful.
