### ISSUE TITLE
Maximum input signal frequency 

### ISSUE THREAD

**Issue by jafal1** [RobTillaart/PCF8591#16]
Hi 

What is the maximum analog input signal frequency?
Thanks in advance

**Comment by RobTillaart** [comment]
Sorry, I missed this issue,
will come back to it asap.

**Comment by RobTillaart** [comment]
> What is the maximum analog input signal frequency?

That depends on a number of factors.

1. The complexity of the signal.
nyquist states you must at least sample with twice the frequency of the highest frequency in the signal. 
So a complex signal that has a 1 kHz sine as highest component, needs at least 2 kHz sampling.
A simple sine wave of 1 kHz also needs at least 2 kHz sampling.
2. The conversion time of the device, this is 90 us, sampling frequency 11 kHz (see snippet datasheet below). 
3. The (I2C) speed you can read out the samples. The max clock is 100 kHz, to read the AD register.
In my tests I could do \> 2000 reads per second at 100 kHz. => 0.5 ms per sample.
Note that is with a maximum load of the processor, so no time to process the incoming data. 
4. Time you need to process a single sample or a block of samples. 
Should ideally be less than the conversion time.

![image](https://github.com/RobTillaart/PCF8591/assets/462844/a38fdcb9-d4d9-4cd7-b633-3aa5742192fb)

![image](https://github.com/RobTillaart/PCF8591/assets/462844/ccbff15e-9602-44b9-af61-2bd832ac5a9f)

So the device can make samples faster (90 us) than I2C can read them (0.5 ms) , so I2C is a limiting factor. 
If you need 7 ms to process a sample, that means you need at least 7.5 ms per sample. 
Add 10% loop overhead ==> 8.3 ms / sample. 
Then the max frequency is about 1000 ms / 8.3 ms = about 120 Hz, so say 100 Hz to be on the safe side.

**Comment by RobTillaart** [comment]
@jafal1 
if this answers your question you may close the issue

**Comment by RobTillaart** [comment]
As I assume the question is solved, I close the issue.
Feel free to reopen if the question remains.
Please study the datasheet carefully as most information is available there.
