### ISSUE TITLE
Lack of precision? Could be user error.

### ISSUE THREAD

**Issue by Hairyloon** [RobTillaart/PCF8591#7]
Hi,
I'm trying to read inputs off a PCF8591 and display the results on an OLED.
If I use your library, then it works, but it's rather woolly and only goes between 0 and 192.
However, if I command it directly, eg: 
```cpp
Wire.beginTransmission(PCF8591); // wake up PCF8591
Wire.write(0x04); // control byte - read ADC0 then auto-increment
Wire.endTransmission(); // end tranmission
Wire.requestFrom(PCF8591, 5);
value0=Wire.read();
etc
```
Then I get a confident full scale deflection on the same circuit, but if I try to start the OLED, then the ADC stops working.

**Comment by RobTillaart** [comment]
Sorry for the late reply, apparently I missed some issues in the past.
I'm checking all my libs for missed issues, so can take a few days

**Comment by RobTillaart** [comment]
@Hairyloon 
Is this issue still valid?

**Comment by RobTillaart** [comment]
If this still is a problem, please reopen the issue.

**Comment by Hairyloon** [comment]
Sorry, I had an accident with the project and it caught fire... I didn't notice you'd responded, but the problem kind of went away.
The project is still on the todo list though, so I may come back to you in due course.

**Comment by RobTillaart** [comment]
> caught fire

Hope there were no substantial losses.

> so I may come back to you in due course.

Feel free to open an issue if the problem is library related. 
Otherwise better discuss the problem on the Arduino forum as there more people are available to help you out.

**Comment by Hairyloon** [comment]
> Hope there were no substantial losses.

Just the two chips. :)
